/**
 * Blueprint library used by the MockAIProvider.
 *
 * Each blueprint is a small "program" that emits a realistic, coherent file
 * set for a domain. This is what makes the demo feel like a real coding agent
 * instead of a lorem-ipsum generator: the produced sites actually render in
 * the live preview, and later edit requests patch these same files.
 *
 * When a real model is connected these blueprints become unnecessary — the
 * provider returns model-authored files in the identical shape.
 */

import type { GeneratedFile } from './AIProvider';

export interface BlueprintContext {
  /** Project/brand name derived from the prompt. */
  brand: string;
  /** Detected domain keyword, e.g. "restaurant". */
  domain: string;
  prompt: string;
}

export interface Blueprint {
  id: string;
  label: string;
  /** Keywords that route a prompt to this blueprint. */
  match: string[];
  entry: string;
  taskTitles: string[];
  /**
   * Generic catch-all. Fallbacks only win when no specific blueprint matches,
   * so "restaurant website" routes to the restaurant blueprint rather than
   * the generic one just because it contains the word "website".
   */
  fallback?: boolean;
  build(ctx: BlueprintContext): GeneratedFile[];
}

/* ------------------------------------------------------------------ */
/* Shared snippets                                                     */
/* ------------------------------------------------------------------ */

const readme = (ctx: BlueprintContext, stack: string, features: string[]): GeneratedFile => ({
  path: 'README.md',
  rationale: 'Project documentation and setup instructions.',
  content: `# ${ctx.brand}

${ctx.prompt.trim()}

## Stack
${stack}

## Features
${features.map((f) => `- ${f}`).join('\n')}

## Getting started
\`\`\`bash
npm install
npm run dev
\`\`\`

## Structure
\`\`\`
index.html        Markup and content sections
styles/main.css   Design system, layout, components
scripts/main.js   Interactions and progressive enhancement
\`\`\`

---
Scaffolded by CodeForge AI.
`,
});

const packageJson = (ctx: BlueprintContext, name: string): GeneratedFile => ({
  path: 'package.json',
  rationale: 'Dependency manifest and scripts.',
  content: `{
  "name": "${name}",
  "version": "0.1.0",
  "private": true,
  "description": "${ctx.brand} — generated by CodeForge AI",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "vitest run"
  },
  "devDependencies": {
    "vite": "^5.4.0",
    "vitest": "^2.1.0"
  }
}
`,
});

/* ------------------------------------------------------------------ */
/* Luxury restaurant                                                   */
/* ------------------------------------------------------------------ */

const restaurant: Blueprint = {
  id: 'luxury-restaurant',
  label: 'Luxury restaurant website',
  match: ['restaurant', 'dining', 'bistro', 'cafe', 'menu', 'food', 'chef', 'culinary', 'eatery'],
  entry: 'index.html',
  taskTitles: [
    'Define brand palette and typography scale',
    'Build hero with reservation call-to-action',
    'Compose signature menu section',
    'Add chef story and testimonials',
    'Wire reservation form validation',
  ],
  build(ctx) {
    const brand = ctx.brand;
    return [
      {
        path: 'index.html',
        rationale: 'Semantic page structure with hero, menu, story, and reservation sections.',
        content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${brand} — Fine Dining</title>
  <meta name="description" content="${brand}: a seasonal tasting menu, rare cellar and quiet luxury in the heart of the city." />
  <link rel="stylesheet" href="styles/main.css" />
</head>
<body>
  <header class="nav" id="nav">
    <a class="nav__brand" href="#top">${brand}</a>
    <nav class="nav__links">
      <a href="#menu">Menu</a>
      <a href="#story">Story</a>
      <a href="#press">Press</a>
      <a href="#reserve" class="btn btn--ghost">Reserve</a>
    </nav>
    <button class="nav__toggle" aria-label="Open menu" aria-expanded="false">
      <span></span><span></span>
    </button>
  </header>

  <main id="top">
    <section class="hero">
      <p class="hero__eyebrow">Est. 1998 &middot; Two Michelin Stars</p>
      <h1 class="hero__title">An evening<br /><em>worth remembering</em></h1>
      <p class="hero__sub">
        Seasonal tasting menus built from coastal produce, aged in-house and served
        beneath candlelight. Twenty-four seats. One nightly service.
      </p>
      <div class="hero__actions">
        <a href="#reserve" class="btn btn--gold">Reserve a table</a>
        <a href="#menu" class="btn btn--outline">View the menu</a>
      </div>
      <dl class="hero__stats">
        <div><dt>Seats</dt><dd>24</dd></div>
        <div><dt>Courses</dt><dd>9</dd></div>
        <div><dt>Cellar</dt><dd>1.2k</dd></div>
      </dl>
    </section>

    <section class="menu" id="menu">
      <div class="section-head">
        <span class="rule"></span>
        <h2>The Autumn Tasting</h2>
        <p>Nine courses, paired on request. Served 18:00 – 22:30.</p>
      </div>
      <div class="menu__grid">
        <article class="dish">
          <h3>Oyster &amp; Green Apple</h3>
          <p>Fine de claire, apple granita, dill oil, finger lime.</p>
          <span class="dish__price">18</span>
        </article>
        <article class="dish">
          <h3>Hand-Dived Scallop</h3>
          <p>Brown butter emulsion, sea herbs, toasted buckwheat.</p>
          <span class="dish__price">26</span>
        </article>
        <article class="dish">
          <h3>Aged Duck, 28 Days</h3>
          <p>Cherry, fermented pepper, duck-fat potato terrine.</p>
          <span class="dish__price">42</span>
        </article>
        <article class="dish">
          <h3>Truffle Agnolotti</h3>
          <p>Winter truffle, parmesan crema, sage.</p>
          <span class="dish__price">38</span>
        </article>
        <article class="dish">
          <h3>Turbot on the Bone</h3>
          <p>Beurre blanc, smoked roe, charred leek.</p>
          <span class="dish__price">46</span>
        </article>
        <article class="dish">
          <h3>Chocolate &amp; Olive</h3>
          <p>Single-origin ganache, olive caramel, sea salt.</p>
          <span class="dish__price">16</span>
        </article>
      </div>
    </section>

    <section class="story" id="story">
      <div class="story__text">
        <span class="rule"></span>
        <h2>From the kitchen</h2>
        <p>
          Chef Amara Lind cooks a single menu each night, written the morning it is served.
          What arrives from the coast at dawn decides what reaches the pass by dusk.
        </p>
        <p>
          The room seats twenty-four. There is no second sitting. Dinner is meant to last.
        </p>
        <p class="signature">— Amara Lind, Executive Chef</p>
      </div>
      <div class="story__panel" aria-hidden="true">
        <div class="story__glow"></div>
      </div>
    </section>

    <section class="press" id="press">
      <blockquote>
        <p>"The most quietly confident dining room in the country."</p>
        <cite>The Continental Review</cite>
      </blockquote>
      <blockquote>
        <p>"Technique in service of pleasure, never the other way around."</p>
        <cite>Saveur Atlas</cite>
      </blockquote>
    </section>

    <section class="reserve" id="reserve">
      <div class="section-head">
        <span class="rule"></span>
        <h2>Reserve</h2>
        <p>Bookings open sixty days ahead. We hold a few seats at the counter for walk-ins.</p>
      </div>
      <form class="reserve__form" id="reservation-form" novalidate>
        <div class="field">
          <label for="name">Name</label>
          <input id="name" name="name" type="text" required placeholder="Full name" />
        </div>
        <div class="field">
          <label for="email">Email</label>
          <input id="email" name="email" type="email" required placeholder="you@example.com" />
        </div>
        <div class="field">
          <label for="date">Date</label>
          <input id="date" name="date" type="date" required />
        </div>
        <div class="field">
          <label for="guests">Guests</label>
          <select id="guests" name="guests">
            <option>2 guests</option>
            <option>3 guests</option>
            <option>4 guests</option>
            <option>6 guests</option>
          </select>
        </div>
        <button class="btn btn--gold btn--wide" type="submit">Request reservation</button>
        <p class="form-status" id="form-status" role="status"></p>
      </form>
    </section>
  </main>

  <footer class="footer">
    <div>
      <strong>${brand}</strong>
      <p>14 Harbour Lane &middot; Open Tuesday – Saturday</p>
    </div>
    <p class="footer__fine">© ${new Date().getFullYear()} ${brand}. All rights reserved.</p>
  </footer>

  <script src="scripts/main.js"></script>
</body>
</html>
`,
      },
      {
        path: 'styles/main.css',
        rationale: 'Design system: gold-on-charcoal palette, serif display type, responsive grid.',
        content: `/* ${brand} — design system */
:root {
  --ink: #0b0b0d;
  --ink-soft: #131317;
  --paper: #f4f1ea;
  --muted: #a5a09a;
  --gold: #c9a227;
  --gold-soft: rgba(201, 162, 39, 0.14);
  --line: rgba(244, 241, 234, 0.12);
  --serif: 'Cormorant Garamond', Georgia, 'Times New Roman', serif;
  --sans: 'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif;
  --max: 1180px;
  --ease: cubic-bezier(0.22, 1, 0.36, 1);
}

* { box-sizing: border-box; }

body {
  margin: 0;
  background: var(--ink);
  color: var(--paper);
  font-family: var(--sans);
  font-size: 16px;
  line-height: 1.65;
  -webkit-font-smoothing: antialiased;
}

h1, h2, h3 { font-family: var(--serif); font-weight: 500; letter-spacing: -0.01em; margin: 0; }
a { color: inherit; text-decoration: none; }

/* Navigation */
.nav {
  position: sticky; top: 0; z-index: 50;
  display: flex; align-items: center; justify-content: space-between;
  padding: 20px 40px;
  background: rgba(11, 11, 13, 0.72);
  backdrop-filter: blur(14px);
  border-bottom: 1px solid var(--line);
}
.nav__brand { font-family: var(--serif); font-size: 22px; letter-spacing: 0.14em; text-transform: uppercase; }
.nav__links { display: flex; align-items: center; gap: 30px; font-size: 13px; letter-spacing: 0.1em; text-transform: uppercase; }
.nav__links a { color: var(--muted); transition: color 0.25s var(--ease); }
.nav__links a:hover { color: var(--gold); }
.nav__toggle { display: none; background: none; border: 0; cursor: pointer; padding: 8px; }
.nav__toggle span { display: block; width: 22px; height: 1px; background: var(--paper); margin: 5px 0; transition: transform 0.3s var(--ease); }

/* Buttons */
.btn {
  display: inline-flex; align-items: center; justify-content: center;
  padding: 13px 26px; border-radius: 2px;
  font-size: 12px; letter-spacing: 0.16em; text-transform: uppercase;
  border: 1px solid transparent; cursor: pointer;
  transition: transform 0.25s var(--ease), background 0.25s var(--ease), color 0.25s var(--ease);
}
.btn:hover { transform: translateY(-2px); }
.btn--gold { background: var(--gold); color: #17130a; font-weight: 600; }
.btn--gold:hover { background: #dcb43a; }
.btn--outline { border-color: var(--line); color: var(--paper); }
.btn--outline:hover { border-color: var(--gold); color: var(--gold); }
.btn--ghost { border: 1px solid var(--gold); color: var(--gold) !important; padding: 9px 18px; }
.btn--wide { width: 100%; grid-column: 1 / -1; }

/* Hero */
.hero {
  max-width: var(--max); margin: 0 auto; padding: 130px 40px 110px; text-align: center;
  background:
    radial-gradient(1000px 460px at 50% -12%, var(--gold-soft), transparent 70%);
}
.hero__eyebrow { color: var(--gold); font-size: 11px; letter-spacing: 0.34em; text-transform: uppercase; margin: 0 0 26px; }
.hero__title { font-size: clamp(48px, 9vw, 104px); line-height: 0.98; }
.hero__title em { font-style: italic; color: var(--gold); }
.hero__sub { max-width: 560px; margin: 30px auto 0; color: var(--muted); font-size: 17px; }
.hero__actions { display: flex; gap: 14px; justify-content: center; flex-wrap: wrap; margin-top: 42px; }
.hero__stats { display: flex; justify-content: center; gap: 64px; margin: 80px 0 0; padding-top: 40px; border-top: 1px solid var(--line); }
.hero__stats div { text-align: center; }
.hero__stats dt { color: var(--muted); font-size: 11px; letter-spacing: 0.22em; text-transform: uppercase; }
.hero__stats dd { font-family: var(--serif); font-size: 40px; margin: 8px 0 0; color: var(--gold); }

/* Section heads */
.section-head { text-align: center; max-width: 620px; margin: 0 auto 62px; }
.section-head h2 { font-size: clamp(34px, 5vw, 52px); margin-bottom: 14px; }
.section-head p { color: var(--muted); margin: 0; }
.rule { display: block; width: 46px; height: 1px; background: var(--gold); margin: 0 auto 26px; }

/* Menu */
.menu { max-width: var(--max); margin: 0 auto; padding: 110px 40px; }
.menu__grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(310px, 1fr)); gap: 2px; background: var(--line); border: 1px solid var(--line); }
.dish {
  position: relative; background: var(--ink); padding: 38px 34px;
  transition: background 0.35s var(--ease);
}
.dish:hover { background: var(--ink-soft); }
.dish h3 { font-size: 25px; padding-right: 52px; }
.dish p { color: var(--muted); font-size: 14.5px; margin: 12px 0 0; }
.dish__price {
  position: absolute; top: 38px; right: 34px;
  font-family: var(--serif); font-size: 22px; color: var(--gold);
}

/* Story */
.story {
  display: grid; grid-template-columns: 1.1fr 0.9fr; gap: 70px; align-items: center;
  max-width: var(--max); margin: 0 auto; padding: 90px 40px;
}
.story__text .rule { margin-left: 0; }
.story__text h2 { font-size: clamp(32px, 4.5vw, 48px); margin-bottom: 22px; }
.story__text p { color: var(--muted); }
.signature { font-family: var(--serif); font-style: italic; color: var(--gold) !important; font-size: 19px; margin-top: 26px !important; }
.story__panel { position: relative; aspect-ratio: 4 / 5; border: 1px solid var(--line); overflow: hidden; }
.story__glow {
  position: absolute; inset: 0;
  background: radial-gradient(420px 420px at 60% 35%, rgba(201,162,39,0.30), transparent 68%),
              linear-gradient(155deg, #16130c, #0b0b0d 62%);
  animation: drift 14s ease-in-out infinite alternate;
}
@keyframes drift { to { transform: scale(1.09) translateY(-14px); } }

/* Press */
.press {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(320px, 1fr)); gap: 40px;
  max-width: var(--max); margin: 0 auto; padding: 70px 40px 110px;
}
.press blockquote { margin: 0; padding: 34px; border-left: 1px solid var(--gold); }
.press p { font-family: var(--serif); font-size: 25px; font-style: italic; margin: 0 0 16px; }
.press cite { color: var(--muted); font-size: 11px; letter-spacing: 0.22em; text-transform: uppercase; font-style: normal; }

/* Reservation */
.reserve { max-width: 780px; margin: 0 auto; padding: 90px 40px 120px; }
.reserve__form { display: grid; grid-template-columns: 1fr 1fr; gap: 22px; }
.field { display: flex; flex-direction: column; gap: 9px; }
.field label { font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase; color: var(--muted); }
.field input, .field select {
  background: transparent; border: 1px solid var(--line); color: var(--paper);
  padding: 14px 16px; border-radius: 2px; font-family: inherit; font-size: 15px;
  transition: border-color 0.25s var(--ease);
}
.field input:focus, .field select:focus { outline: none; border-color: var(--gold); }
.field input.invalid { border-color: #c0483c; }
.form-status { grid-column: 1 / -1; text-align: center; margin: 4px 0 0; min-height: 22px; font-size: 14px; color: var(--gold); }

/* Footer */
.footer {
  display: flex; justify-content: space-between; align-items: center; gap: 20px; flex-wrap: wrap;
  max-width: var(--max); margin: 0 auto; padding: 44px 40px;
  border-top: 1px solid var(--line); color: var(--muted); font-size: 13px;
}
.footer strong { font-family: var(--serif); font-size: 19px; color: var(--paper); letter-spacing: 0.1em; }
.footer p { margin: 6px 0 0; }

/* Reveal animation */
.reveal { opacity: 0; transform: translateY(26px); transition: opacity 0.8s var(--ease), transform 0.8s var(--ease); }
.reveal.visible { opacity: 1; transform: none; }

/* Responsive */
@media (max-width: 900px) {
  .story { grid-template-columns: 1fr; gap: 44px; }
  .story__panel { aspect-ratio: 16 / 10; }
}
@media (max-width: 720px) {
  .nav { padding: 16px 22px; }
  .nav__links { display: none; }
  .nav__links.open {
    display: flex; flex-direction: column; gap: 18px;
    position: absolute; top: 100%; left: 0; right: 0;
    background: var(--ink); padding: 26px; border-bottom: 1px solid var(--line);
  }
  .nav__toggle { display: block; }
  .hero { padding: 84px 22px 70px; }
  .hero__stats { gap: 32px; }
  .menu, .story, .press, .reserve { padding-left: 22px; padding-right: 22px; }
  .reserve__form { grid-template-columns: 1fr; }
}
@media (prefers-reduced-motion: reduce) {
  * { animation: none !important; transition: none !important; }
  .reveal { opacity: 1; transform: none; }
}
`,
      },
      {
        path: 'scripts/main.js',
        rationale: 'Scroll reveals, mobile navigation, and reservation form validation.',
        content: `// ${brand} — interactions
(function () {
  'use strict';

  /* Mobile navigation ------------------------------------------------ */
  var toggle = document.querySelector('.nav__toggle');
  var links = document.querySelector('.nav__links');
  if (toggle && links) {
    toggle.addEventListener('click', function () {
      var open = links.classList.toggle('open');
      toggle.setAttribute('aria-expanded', String(open));
    });
    links.addEventListener('click', function (e) {
      if (e.target.tagName === 'A') {
        links.classList.remove('open');
        toggle.setAttribute('aria-expanded', 'false');
      }
    });
  }

  /* Smooth anchor scrolling ------------------------------------------ */
  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      var id = anchor.getAttribute('href');
      if (!id || id === '#') return;
      var target = document.querySelector(id);
      if (!target) return;
      e.preventDefault();
      target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  });

  /* Scroll reveal ----------------------------------------------------- */
  var revealables = document.querySelectorAll('.dish, .section-head, .story__text, .press blockquote, .hero__stats');
  revealables.forEach(function (el) { el.classList.add('reveal'); });

  if ('IntersectionObserver' in window) {
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry, i) {
        if (!entry.isIntersecting) return;
        setTimeout(function () { entry.target.classList.add('visible'); }, i * 70);
        io.unobserve(entry.target);
      });
    }, { threshold: 0.14, rootMargin: '0px 0px -40px 0px' });
    revealables.forEach(function (el) { io.observe(el); });
  } else {
    revealables.forEach(function (el) { el.classList.add('visible'); });
  }

  /* Reservation form -------------------------------------------------- */
  var form = document.getElementById('reservation-form');
  var status = document.getElementById('form-status');

  function isEmail(value) {
    return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$/.test(value);
  }

  if (form && status) {
    form.addEventListener('submit', function (e) {
      e.preventDefault();
      var name = form.querySelector('#name');
      var email = form.querySelector('#email');
      var date = form.querySelector('#date');
      var problems = [];

      [name, email, date].forEach(function (f) { f.classList.remove('invalid'); });

      if (!name.value.trim()) { problems.push('name'); name.classList.add('invalid'); }
      if (!isEmail(email.value.trim())) { problems.push('a valid email'); email.classList.add('invalid'); }
      if (!date.value) { problems.push('a date'); date.classList.add('invalid'); }

      if (problems.length) {
        status.textContent = 'Please provide ' + problems.join(', ') + '.';
        status.style.color = '#c0483c';
        return;
      }

      status.style.color = '';
      status.textContent = 'Thank you, ' + name.value.trim() + '. We will confirm by email shortly.';
      form.reset();
    });
  }
})();
`,
      },
      {
        path: 'tests/reservation.test.js',
        rationale: 'Unit tests for reservation validation helpers.',
        content: `import { describe, it, expect } from 'vitest';

function isEmail(value) {
  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$/.test(value);
}

function validateReservation({ name, email, date, guests }) {
  const errors = [];
  if (!name || !name.trim()) errors.push('name');
  if (!isEmail(email || '')) errors.push('email');
  if (!date) errors.push('date');
  if (guests != null && (guests < 1 || guests > 12)) errors.push('guests');
  return { valid: errors.length === 0, errors };
}

describe('reservation validation', () => {
  it('accepts a complete booking', () => {
    const r = validateReservation({ name: 'Ada', email: 'ada@example.com', date: '2026-01-20', guests: 2 });
    expect(r.valid).toBe(true);
  });

  it('rejects a malformed email', () => {
    const r = validateReservation({ name: 'Ada', email: 'ada@', date: '2026-01-20' });
    expect(r.errors).toContain('email');
  });

  it('requires a date', () => {
    const r = validateReservation({ name: 'Ada', email: 'ada@example.com', date: '' });
    expect(r.errors).toContain('date');
  });

  it('bounds party size', () => {
    const r = validateReservation({ name: 'Ada', email: 'ada@example.com', date: '2026-01-20', guests: 40 });
    expect(r.errors).toContain('guests');
  });
});
`,
      },
      packageJson(ctx, 'luxury-restaurant'),
      readme(ctx, '- Vanilla HTML/CSS/JS (zero runtime dependencies)\n- Vite dev server\n- Vitest for unit tests', [
        'Responsive luxury layout with gold-on-charcoal palette',
        'Sticky navigation with mobile drawer',
        'Scroll-reveal animations (respects reduced-motion)',
        'Client-side reservation form validation',
      ]),
    ];
  },
};

/* ------------------------------------------------------------------ */
/* SaaS landing page                                                   */
/* ------------------------------------------------------------------ */

const landing: Blueprint = {
  id: 'saas-landing',
  label: 'SaaS landing page',
  match: ['landing', 'saas', 'startup', 'product page', 'marketing', 'waitlist', 'pricing'],
  entry: 'index.html',
  taskTitles: [
    'Set up gradient design tokens',
    'Build hero with waitlist capture',
    'Create feature grid',
    'Add pricing tiers',
    'Wire email capture validation',
  ],
  build(ctx) {
    const brand = ctx.brand;
    return [
      {
        path: 'index.html',
        rationale: 'Landing page structure: hero, features, pricing, CTA.',
        content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${brand} — Ship faster</title>
  <link rel="stylesheet" href="styles/main.css" />
</head>
<body>
  <header class="nav">
    <span class="logo">${brand}</span>
    <nav>
      <a href="#features">Features</a>
      <a href="#pricing">Pricing</a>
      <a href="#cta" class="btn btn--sm">Get started</a>
    </nav>
  </header>

  <section class="hero">
    <span class="pill">v2.0 is live</span>
    <h1>Build products<br /><span class="grad">at the speed of thought</span></h1>
    <p>${brand} gives your team one workspace for planning, shipping and measuring. No more context switching.</p>
    <form class="capture" id="capture">
      <input type="email" id="email" placeholder="you@company.com" aria-label="Work email" />
      <button class="btn" type="submit">Start free</button>
    </form>
    <p class="note" id="note">Free for 14 days · No card required</p>
  </section>

  <section class="features" id="features">
    <h2>Everything, in one place</h2>
    <div class="grid">
      <article><div class="ico">◆</div><h3>Instant deploys</h3><p>Push to main and ship to production in under forty seconds.</p></article>
      <article><div class="ico">◈</div><h3>Live collaboration</h3><p>Cursors, comments and reviews without leaving the editor.</p></article>
      <article><div class="ico">◇</div><h3>Deep insight</h3><p>Track adoption, latency and errors on one shared dashboard.</p></article>
      <article><div class="ico">▣</div><h3>Enterprise ready</h3><p>SSO, audit logs, SOC 2 Type II and regional data residency.</p></article>
    </div>
  </section>

  <section class="pricing" id="pricing">
    <h2>Simple pricing</h2>
    <div class="tiers">
      <article class="tier"><h3>Starter</h3><p class="price">$0<span>/mo</span></p><ul><li>3 projects</li><li>Community support</li><li>1 GB storage</li></ul><a href="#cta" class="btn btn--outline">Choose</a></article>
      <article class="tier tier--hot"><span class="tag">Popular</span><h3>Team</h3><p class="price">$24<span>/mo</span></p><ul><li>Unlimited projects</li><li>Priority support</li><li>100 GB storage</li></ul><a href="#cta" class="btn">Choose</a></article>
      <article class="tier"><h3>Scale</h3><p class="price">$79<span>/mo</span></p><ul><li>SSO &amp; audit logs</li><li>Dedicated manager</li><li>1 TB storage</li></ul><a href="#cta" class="btn btn--outline">Choose</a></article>
    </div>
  </section>

  <section class="cta" id="cta">
    <h2>Ready when you are</h2>
    <p>Join 12,000 teams already shipping with ${brand}.</p>
    <a href="#capture" class="btn btn--lg">Create your workspace</a>
  </section>

  <footer><p>© ${new Date().getFullYear()} ${brand}</p></footer>
  <script src="scripts/main.js"></script>
</body>
</html>
`,
      },
      {
        path: 'styles/main.css',
        rationale: 'Gradient-forward dark design system with responsive grids.',
        content: `:root {
  --bg: #08090d; --card: #101219; --line: rgba(255,255,255,0.08);
  --text: #e8eaf0; --muted: #8b90a0;
  --a: #6366f1; --b: #a855f7; --c: #22d3ee;
  --ease: cubic-bezier(0.22,1,0.36,1);
}
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--text); font-family: 'Inter', system-ui, sans-serif; line-height:1.6; }
a { color:inherit; text-decoration:none; }
h1,h2,h3 { margin:0; letter-spacing:-0.03em; }

.nav { display:flex; justify-content:space-between; align-items:center; padding:20px 40px; border-bottom:1px solid var(--line); position:sticky; top:0; background:rgba(8,9,13,0.8); backdrop-filter:blur(12px); z-index:20; }
.logo { font-weight:700; font-size:19px; }
.nav nav { display:flex; gap:26px; align-items:center; font-size:14px; color:var(--muted); }
.nav nav a:hover { color:var(--text); }

.btn { display:inline-flex; align-items:center; justify-content:center; padding:12px 22px; border-radius:10px; background:linear-gradient(120deg,var(--a),var(--b)); color:#fff; font-weight:600; font-size:14px; border:0; cursor:pointer; transition:transform .22s var(--ease), box-shadow .22s var(--ease); }
.btn:hover { transform:translateY(-2px); box-shadow:0 14px 34px rgba(99,102,241,0.34); }
.btn--sm { padding:9px 16px; font-size:13px; }
.btn--lg { padding:16px 34px; font-size:16px; }
.btn--outline { background:transparent; border:1px solid var(--line); }

.hero { text-align:center; padding:112px 24px 92px; background:radial-gradient(900px 420px at 50% -10%, rgba(99,102,241,0.20), transparent 70%); }
.pill { display:inline-block; padding:6px 14px; border-radius:999px; border:1px solid var(--line); font-size:12px; color:var(--muted); margin-bottom:26px; }
.hero h1 { font-size:clamp(40px,7vw,72px); line-height:1.06; }
.grad { background:linear-gradient(120deg,var(--a),var(--b) 45%,var(--c)); -webkit-background-clip:text; background-clip:text; color:transparent; }
.hero p { color:var(--muted); max-width:540px; margin:22px auto 0; font-size:17px; }
.capture { display:flex; gap:10px; max-width:440px; margin:36px auto 0; }
.capture input { flex:1; padding:13px 16px; border-radius:10px; border:1px solid var(--line); background:var(--card); color:var(--text); font-size:15px; }
.capture input:focus { outline:none; border-color:var(--a); }
.capture input.bad { border-color:#ef4444; }
.note { font-size:13px !important; margin-top:14px !important; min-height:20px; }

.features, .pricing { max-width:1120px; margin:0 auto; padding:90px 24px; }
.features h2, .pricing h2, .cta h2 { font-size:clamp(30px,4.5vw,44px); text-align:center; margin-bottom:48px; }
.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(250px,1fr)); gap:20px; }
.grid article { background:var(--card); border:1px solid var(--line); border-radius:16px; padding:28px; transition:transform .3s var(--ease), border-color .3s var(--ease); }
.grid article:hover { transform:translateY(-5px); border-color:rgba(99,102,241,0.5); }
.ico { width:42px; height:42px; display:grid; place-items:center; border-radius:11px; background:linear-gradient(120deg,var(--a),var(--b)); font-size:18px; margin-bottom:16px; }
.grid h3 { font-size:18px; margin-bottom:8px; }
.grid p { color:var(--muted); font-size:14.5px; margin:0; }

.tiers { display:grid; grid-template-columns:repeat(auto-fit,minmax(270px,1fr)); gap:22px; }
.tier { position:relative; background:var(--card); border:1px solid var(--line); border-radius:18px; padding:32px; text-align:center; }
.tier--hot { border-color:var(--a); box-shadow:0 22px 60px rgba(99,102,241,0.20); }
.tag { position:absolute; top:-11px; left:50%; transform:translateX(-50%); background:linear-gradient(120deg,var(--a),var(--b)); padding:4px 14px; border-radius:999px; font-size:11px; font-weight:600; }
.price { font-size:44px; font-weight:700; margin:14px 0 20px; }
.price span { font-size:15px; color:var(--muted); font-weight:400; }
.tier ul { list-style:none; padding:0; margin:0 0 24px; color:var(--muted); font-size:14.5px; }
.tier li { padding:7px 0; border-bottom:1px solid var(--line); }

.cta { text-align:center; padding:96px 24px; background:radial-gradient(700px 320px at 50% 50%, rgba(168,85,247,0.16), transparent 70%); }
.cta p { color:var(--muted); margin:0 0 30px; }
footer { text-align:center; padding:34px; border-top:1px solid var(--line); color:var(--muted); font-size:13px; }

@media (max-width:640px) {
  .nav { padding:16px 20px; } .nav nav { gap:16px; }
  .capture { flex-direction:column; }
}
`,
      },
      {
        path: 'scripts/main.js',
        rationale: 'Email capture validation and scroll reveals.',
        content: `(function () {
  'use strict';
  var form = document.getElementById('capture');
  var input = document.getElementById('email');
  var note = document.getElementById('note');

  function isEmail(v) { return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$/.test(v); }

  if (form) {
    form.addEventListener('submit', function (e) {
      e.preventDefault();
      var v = input.value.trim();
      input.classList.remove('bad');
      if (!isEmail(v)) {
        input.classList.add('bad');
        note.textContent = 'Please enter a valid work email.';
        note.style.color = '#ef4444';
        return;
      }
      note.style.color = '#22d3ee';
      note.textContent = "You're on the list. Check " + v + ' for your invite.';
      form.reset();
    });
  }

  var cards = document.querySelectorAll('.grid article, .tier');
  if ('IntersectionObserver' in window) {
    cards.forEach(function (c) { c.style.opacity = '0'; c.style.transform = 'translateY(20px)'; c.style.transition = 'opacity .6s ease, transform .6s ease'; });
    var io = new IntersectionObserver(function (es) {
      es.forEach(function (e, i) {
        if (!e.isIntersecting) return;
        setTimeout(function () { e.target.style.opacity = '1'; e.target.style.transform = 'none'; }, i * 80);
        io.unobserve(e.target);
      });
    }, { threshold: 0.15 });
    cards.forEach(function (c) { io.observe(c); });
  }
})();
`,
      },
      {
        path: 'tests/capture.test.js',
        rationale: 'Validates the email capture helper.',
        content: `import { describe, it, expect } from 'vitest';

const isEmail = (v) => /^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$/.test(v);

describe('email capture', () => {
  it('accepts a work email', () => expect(isEmail('sam@acme.io')).toBe(true));
  it('rejects a missing domain', () => expect(isEmail('sam@')).toBe(false));
  it('rejects empty input', () => expect(isEmail('')).toBe(false));
});
`,
      },
      packageJson(ctx, 'saas-landing'),
      readme(ctx, '- Vanilla HTML/CSS/JS\n- Vite\n- Vitest', [
        'Gradient hero with waitlist capture',
        'Feature and pricing grids',
        'Scroll-reveal animations',
      ]),
    ];
  },
};

/* ------------------------------------------------------------------ */
/* Analytics dashboard                                                 */
/* ------------------------------------------------------------------ */

const dashboard: Blueprint = {
  id: 'analytics-dashboard',
  label: 'Analytics dashboard',
  match: ['dashboard', 'analytics', 'admin', 'metrics', 'chart', 'kpi', 'report', 'crm'],
  entry: 'index.html',
  taskTitles: [
    'Create layout shell with sidebar',
    'Build KPI stat cards',
    'Render SVG trend chart',
    'Add sortable data table',
    'Wire mock data service',
  ],
  build(ctx) {
    const brand = ctx.brand;
    return [
      {
        path: 'index.html',
        rationale: 'Dashboard shell: sidebar, KPI row, chart, table.',
        content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${brand} — Dashboard</title>
  <link rel="stylesheet" href="styles/main.css" />
</head>
<body>
  <div class="app">
    <aside class="side">
      <div class="side__logo">${brand}</div>
      <nav>
        <a class="active" href="#">Overview</a>
        <a href="#">Revenue</a>
        <a href="#">Customers</a>
        <a href="#">Reports</a>
        <a href="#">Settings</a>
      </nav>
    </aside>
    <main class="main">
      <header class="head">
        <div><h1>Overview</h1><p>Last 30 days</p></div>
        <button class="btn" id="refresh">Refresh</button>
      </header>
      <section class="kpis" id="kpis"></section>
      <section class="panel">
        <h2>Revenue trend</h2>
        <div id="chart"></div>
      </section>
      <section class="panel">
        <h2>Recent orders</h2>
        <table id="table">
          <thead><tr><th data-k="id">Order</th><th data-k="customer">Customer</th><th data-k="total">Total</th><th data-k="status">Status</th></tr></thead>
          <tbody></tbody>
        </table>
      </section>
    </main>
  </div>
  <script src="scripts/data.js"></script>
  <script src="scripts/main.js"></script>
</body>
</html>
`,
      },
      {
        path: 'styles/main.css',
        rationale: 'Dashboard design system with responsive collapse.',
        content: `:root { --bg:#0a0b0f; --panel:#111319; --line:rgba(255,255,255,0.07); --text:#e6e8ee; --muted:#868c9b; --accent:#3b82f6; --good:#22c55e; --bad:#ef4444; }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--text); font-family:'Inter',system-ui,sans-serif; font-size:15px; }
.app { display:grid; grid-template-columns:230px 1fr; min-height:100vh; }
.side { border-right:1px solid var(--line); padding:24px 16px; background:#0c0d12; }
.side__logo { font-weight:700; font-size:18px; padding:0 12px 22px; }
.side nav { display:flex; flex-direction:column; gap:4px; }
.side a { padding:10px 12px; border-radius:8px; color:var(--muted); text-decoration:none; font-size:14px; transition:background .2s, color .2s; }
.side a:hover { background:rgba(255,255,255,0.04); color:var(--text); }
.side a.active { background:rgba(59,130,246,0.14); color:#93c5fd; }
.main { padding:28px 32px 60px; }
.head { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:26px; }
.head h1 { margin:0; font-size:26px; }
.head p { margin:4px 0 0; color:var(--muted); font-size:13px; }
.btn { background:var(--accent); color:#fff; border:0; padding:10px 18px; border-radius:8px; font-size:14px; font-weight:500; cursor:pointer; transition:filter .2s, transform .2s; }
.btn:hover { filter:brightness(1.12); transform:translateY(-1px); }
.kpis { display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:16px; margin-bottom:22px; }
.kpi { background:var(--panel); border:1px solid var(--line); border-radius:14px; padding:20px; }
.kpi__label { color:var(--muted); font-size:12.5px; text-transform:uppercase; letter-spacing:.08em; }
.kpi__value { font-size:29px; font-weight:650; margin:8px 0 6px; }
.kpi__delta { font-size:13px; font-weight:500; }
.kpi__delta.up { color:var(--good); } .kpi__delta.down { color:var(--bad); }
.panel { background:var(--panel); border:1px solid var(--line); border-radius:14px; padding:22px; margin-bottom:20px; }
.panel h2 { margin:0 0 18px; font-size:16px; font-weight:600; }
table { width:100%; border-collapse:collapse; font-size:14px; }
th { text-align:left; color:var(--muted); font-weight:500; font-size:12.5px; text-transform:uppercase; letter-spacing:.06em; padding:0 12px 12px; cursor:pointer; user-select:none; }
th:hover { color:var(--text); }
td { padding:13px 12px; border-top:1px solid var(--line); }
.badge { padding:3px 10px; border-radius:999px; font-size:12px; }
.badge.paid { background:rgba(34,197,94,.14); color:#4ade80; }
.badge.pending { background:rgba(234,179,8,.14); color:#facc15; }
.badge.failed { background:rgba(239,68,68,.14); color:#f87171; }
svg .line { fill:none; stroke:var(--accent); stroke-width:2.5; stroke-linecap:round; stroke-linejoin:round; }
svg .area { fill:url(#g); }
@media (max-width:820px) {
  .app { grid-template-columns:1fr; }
  .side { border-right:0; border-bottom:1px solid var(--line); }
  .side nav { flex-direction:row; overflow-x:auto; }
  .main { padding:20px; }
}
`,
      },
      {
        path: 'scripts/data.js',
        rationale: 'Mock data source — swap for a real API client later.',
        content: `// Replace these functions with real fetch() calls to your API.
window.DataService = {
  getKpis: function () {
    return [
      { label: 'Revenue', value: '$284,120', delta: 12.4 },
      { label: 'Orders', value: '3,842', delta: 8.1 },
      { label: 'Customers', value: '1,204', delta: 4.6 },
      { label: 'Churn', value: '2.1%', delta: -0.8 }
    ];
  },
  getTrend: function () {
    return [42, 51, 47, 63, 58, 72, 69, 84, 78, 92, 88, 104];
  },
  getOrders: function () {
    return [
      { id: '#4821', customer: 'Nadia Rahman', total: 1280, status: 'paid' },
      { id: '#4820', customer: 'Yusuf Karim', total: 340, status: 'pending' },
      { id: '#4819', customer: 'Elena Voss', total: 2150, status: 'paid' },
      { id: '#4818', customer: 'Marcus Reed', total: 90, status: 'failed' },
      { id: '#4817', customer: 'Aisha Noor', total: 760, status: 'paid' }
    ];
  }
};
`,
      },
      {
        path: 'scripts/main.js',
        rationale: 'Renders KPIs, the SVG chart and the sortable table.',
        content: `(function () {
  'use strict';
  var D = window.DataService;

  function renderKpis() {
    document.getElementById('kpis').innerHTML = D.getKpis().map(function (k) {
      var dir = k.delta >= 0 ? 'up' : 'down';
      var arrow = k.delta >= 0 ? '▲' : '▼';
      return '<div class="kpi"><div class="kpi__label">' + k.label + '</div>' +
             '<div class="kpi__value">' + k.value + '</div>' +
             '<div class="kpi__delta ' + dir + '">' + arrow + ' ' + Math.abs(k.delta) + '%</div></div>';
    }).join('');
  }

  function renderChart() {
    var data = D.getTrend();
    var w = 720, h = 220, pad = 20;
    var max = Math.max.apply(null, data) * 1.1;
    var step = (w - pad * 2) / (data.length - 1);
    var pts = data.map(function (v, i) {
      return [pad + i * step, h - pad - (v / max) * (h - pad * 2)];
    });
    var line = pts.map(function (p, i) { return (i ? 'L' : 'M') + p[0].toFixed(1) + ' ' + p[1].toFixed(1); }).join(' ');
    var area = line + ' L' + pts[pts.length - 1][0].toFixed(1) + ' ' + (h - pad) + ' L' + pad + ' ' + (h - pad) + ' Z';
    document.getElementById('chart').innerHTML =
      '<svg viewBox="0 0 ' + w + ' ' + h + '" width="100%" height="220" preserveAspectRatio="none">' +
      '<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1">' +
      '<stop offset="0%" stop-color="#3b82f6" stop-opacity="0.35"/>' +
      '<stop offset="100%" stop-color="#3b82f6" stop-opacity="0"/></linearGradient></defs>' +
      '<path class="area" d="' + area + '"/><path class="line" d="' + line + '"/></svg>';
  }

  var sortKey = null, sortAsc = true;
  function renderTable() {
    var rows = D.getOrders().slice();
    if (sortKey) {
      rows.sort(function (a, b) {
        var x = a[sortKey], y = b[sortKey];
        if (x < y) return sortAsc ? -1 : 1;
        if (x > y) return sortAsc ? 1 : -1;
        return 0;
      });
    }
    document.querySelector('#table tbody').innerHTML = rows.map(function (r) {
      return '<tr><td>' + r.id + '</td><td>' + r.customer + '</td><td>$' +
             r.total.toLocaleString() + '</td><td><span class="badge ' + r.status + '">' +
             r.status + '</span></td></tr>';
    }).join('');
  }

  document.querySelectorAll('#table th').forEach(function (th) {
    th.addEventListener('click', function () {
      var k = th.dataset.k;
      sortAsc = sortKey === k ? !sortAsc : true;
      sortKey = k;
      renderTable();
    });
  });

  document.getElementById('refresh').addEventListener('click', function () {
    renderKpis(); renderChart(); renderTable();
  });

  renderKpis(); renderChart(); renderTable();
})();
`,
      },
      {
        path: 'tests/format.test.js',
        rationale: 'Tests numeric formatting helpers.',
        content: `import { describe, it, expect } from 'vitest';

const pct = (n) => (n >= 0 ? '+' : '') + n.toFixed(1) + '%';
const money = (n) => '$' + n.toLocaleString('en-US');

describe('formatting', () => {
  it('formats positive deltas', () => expect(pct(12.4)).toBe('+12.4%'));
  it('formats negative deltas', () => expect(pct(-0.8)).toBe('-0.8%'));
  it('formats currency', () => expect(money(1280)).toBe('$1,280'));
});
`,
      },
      packageJson(ctx, 'analytics-dashboard'),
      readme(ctx, '- Vanilla HTML/CSS/JS\n- Hand-rolled SVG charting\n- Vitest', [
        'KPI cards with trend deltas',
        'SVG area chart',
        'Sortable orders table',
        'Swappable mock data service',
      ]),
    ];
  },
};

/* ------------------------------------------------------------------ */
/* Portfolio (generic fallback)                                        */
/* ------------------------------------------------------------------ */

const portfolio: Blueprint = {
  id: 'generic-site',
  label: 'Modern website',
  match: ['portfolio', 'agency', 'personal', 'blog', 'site', 'website', 'page', 'photographer'],
  entry: 'index.html',
  fallback: true,
  taskTitles: [
    'Establish typography and colour tokens',
    'Build hero section',
    'Add content sections',
    'Add contact block',
    'Polish responsive behaviour',
  ],
  build(ctx) {
    const brand = ctx.brand;
    return [
      {
        path: 'index.html',
        rationale: 'Single-page structure tailored to the request.',
        content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${brand}</title>
  <link rel="stylesheet" href="styles/main.css" />
</head>
<body>
  <header class="nav"><span class="logo">${brand}</span>
    <nav><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></nav>
  </header>

  <section class="hero">
    <h1>${brand}</h1>
    <p>${ctx.prompt.trim()}</p>
    <a href="#work" class="btn">Explore</a>
  </section>

  <section class="work" id="work">
    <h2>Selected work</h2>
    <div class="grid">
      <article><h3>Project Aurora</h3><p>Brand system and product site for a climate startup.</p></article>
      <article><h3>Meridian</h3><p>Editorial platform serving four million monthly readers.</p></article>
      <article><h3>Halcyon</h3><p>Design language and component library for fintech.</p></article>
      <article><h3>Northwind</h3><p>End-to-end commerce experience with same-day fulfilment.</p></article>
    </div>
  </section>

  <section class="about" id="about">
    <h2>About</h2>
    <p>We are a small studio focused on clarity, craft and measurable outcomes. Every engagement starts with a question and ends with something shipped.</p>
  </section>

  <section class="contact" id="contact">
    <h2>Get in touch</h2>
    <form id="contact-form">
      <input id="cname" placeholder="Your name" aria-label="Name" />
      <input id="cmail" type="email" placeholder="Email" aria-label="Email" />
      <textarea id="cmsg" rows="4" placeholder="Tell us about the project" aria-label="Message"></textarea>
      <button class="btn" type="submit">Send message</button>
      <p class="status" id="cstatus" role="status"></p>
    </form>
  </section>

  <footer><p>© ${new Date().getFullYear()} ${brand}</p></footer>
  <script src="scripts/main.js"></script>
</body>
</html>
`,
      },
      {
        path: 'styles/main.css',
        rationale: 'Clean modern dark theme with responsive grid.',
        content: `:root { --bg:#0a0a0c; --card:#131317; --line:rgba(255,255,255,0.08); --text:#eceef2; --muted:#8b8f99; --accent:#f97316; --ease:cubic-bezier(.22,1,.36,1); }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--text); font-family:'Inter',system-ui,sans-serif; line-height:1.65; }
a { color:inherit; text-decoration:none; }
h1,h2,h3 { margin:0; letter-spacing:-0.02em; }
.nav { display:flex; justify-content:space-between; align-items:center; padding:22px 40px; border-bottom:1px solid var(--line); position:sticky; top:0; background:rgba(10,10,12,.82); backdrop-filter:blur(12px); z-index:10; }
.logo { font-weight:700; font-size:18px; letter-spacing:-0.02em; }
.nav nav { display:flex; gap:26px; font-size:14px; color:var(--muted); }
.nav nav a:hover { color:var(--accent); }
.btn { display:inline-block; padding:13px 26px; border-radius:10px; background:var(--accent); color:#150c04; font-weight:600; font-size:14px; border:0; cursor:pointer; transition:transform .22s var(--ease), filter .22s; }
.btn:hover { transform:translateY(-2px); filter:brightness(1.08); }
.hero { padding:120px 40px 96px; max-width:900px; margin:0 auto; text-align:center; background:radial-gradient(760px 340px at 50% -10%, rgba(249,115,22,.14), transparent 70%); }
.hero h1 { font-size:clamp(42px,8vw,80px); line-height:1.04; }
.hero p { color:var(--muted); font-size:18px; max-width:600px; margin:22px auto 34px; }
.work, .about, .contact { max-width:1060px; margin:0 auto; padding:80px 40px; }
h2 { font-size:clamp(28px,4vw,40px); margin-bottom:36px; }
.grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); gap:18px; }
.grid article { background:var(--card); border:1px solid var(--line); border-radius:16px; padding:26px; transition:transform .3s var(--ease), border-color .3s; }
.grid article:hover { transform:translateY(-4px); border-color:rgba(249,115,22,.45); }
.grid h3 { font-size:19px; margin-bottom:8px; }
.grid p { color:var(--muted); font-size:14.5px; margin:0; }
.about p { color:var(--muted); font-size:17px; max-width:680px; }
#contact-form { display:flex; flex-direction:column; gap:14px; max-width:520px; }
input, textarea { background:var(--card); border:1px solid var(--line); border-radius:10px; padding:13px 16px; color:var(--text); font-family:inherit; font-size:15px; resize:vertical; }
input:focus, textarea:focus { outline:none; border-color:var(--accent); }
input.bad, textarea.bad { border-color:#ef4444; }
.status { min-height:20px; font-size:14px; color:var(--accent); margin:0; }
footer { text-align:center; padding:36px; border-top:1px solid var(--line); color:var(--muted); font-size:13px; }
@media (max-width:640px) { .nav { padding:16px 20px; } .work,.about,.contact { padding:56px 20px; } .hero { padding:80px 20px 64px; } }
`,
      },
      {
        path: 'scripts/main.js',
        rationale: 'Contact form validation and reveal animations.',
        content: `(function () {
  'use strict';
  var form = document.getElementById('contact-form');
  var status = document.getElementById('cstatus');
  function isEmail(v) { return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$/.test(v); }

  if (form) {
    form.addEventListener('submit', function (e) {
      e.preventDefault();
      var n = document.getElementById('cname'), m = document.getElementById('cmail'), g = document.getElementById('cmsg');
      [n, m, g].forEach(function (f) { f.classList.remove('bad'); });
      var bad = [];
      if (!n.value.trim()) { bad.push('name'); n.classList.add('bad'); }
      if (!isEmail(m.value.trim())) { bad.push('email'); m.classList.add('bad'); }
      if (g.value.trim().length < 10) { bad.push('a longer message'); g.classList.add('bad'); }
      if (bad.length) { status.style.color = '#ef4444'; status.textContent = 'Please provide ' + bad.join(', ') + '.'; return; }
      status.style.color = ''; status.textContent = 'Thanks — we will reply within two business days.';
      form.reset();
    });
  }

  var cards = document.querySelectorAll('.grid article');
  if ('IntersectionObserver' in window) {
    cards.forEach(function (c) { c.style.opacity = '0'; c.style.transform = 'translateY(18px)'; c.style.transition = 'opacity .6s ease, transform .6s ease'; });
    var io = new IntersectionObserver(function (es) {
      es.forEach(function (e, i) {
        if (!e.isIntersecting) return;
        setTimeout(function () { e.target.style.opacity = '1'; e.target.style.transform = 'none'; }, i * 70);
        io.unobserve(e.target);
      });
    }, { threshold: .15 });
    cards.forEach(function (c) { io.observe(c); });
  }
})();
`,
      },
      {
        path: 'tests/contact.test.js',
        rationale: 'Tests contact form validation rules.',
        content: `import { describe, it, expect } from 'vitest';

const isEmail = (v) => /^[^\\s@]+@[^\\s@]+\\.[^\\s@]{2,}$/.test(v);
const validate = ({ name, email, message }) => {
  const errors = [];
  if (!name?.trim()) errors.push('name');
  if (!isEmail(email ?? '')) errors.push('email');
  if ((message ?? '').trim().length < 10) errors.push('message');
  return { valid: errors.length === 0, errors };
};

describe('contact form', () => {
  it('accepts valid input', () => {
    expect(validate({ name: 'Ada', email: 'a@b.co', message: 'Hello there team' }).valid).toBe(true);
  });
  it('rejects short messages', () => {
    expect(validate({ name: 'Ada', email: 'a@b.co', message: 'hi' }).errors).toContain('message');
  });
});
`,
      },
      packageJson(ctx, 'modern-site'),
      readme(ctx, '- Vanilla HTML/CSS/JS\n- Vite\n- Vitest', [
        'Responsive single-page layout',
        'Scroll-reveal cards',
        'Validated contact form',
      ]),
    ];
  },
};

export const BLUEPRINTS: Blueprint[] = [restaurant, landing, dashboard, portfolio];

/**
 * Routes a free-text prompt to the best-matching blueprint.
 *
 * Specific blueprints are scored first; the generic fallback is only used when
 * nothing specific matches. Matching is word-boundary aware so "website" does
 * not spuriously match the keyword "site".
 */
export function selectBlueprint(prompt: string): Blueprint {
  const p = prompt.toLowerCase();

  const score = (bp: Blueprint) => {
    let total = 0;
    for (const kw of bp.match) {
      // Escape regex metacharacters, then require whole-word matches.
      const safe = kw.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      if (new RegExp(`\\b${safe}\\b`).test(p)) total += kw.length;
    }
    return total;
  };

  const specific = BLUEPRINTS.filter((b) => !b.fallback);
  let best: Blueprint | null = null;
  let bestScore = 0;

  for (const bp of specific) {
    const s = score(bp);
    if (s > bestScore) {
      bestScore = s;
      best = bp;
    }
  }

  if (best) return best;

  // Nothing specific matched — use the generic blueprint.
  return BLUEPRINTS.find((b) => b.fallback) ?? portfolio;
}
